### PR TITLE
chore: update release flow for node, remove nest.land

### PR DESCRIPTION
**Pull request by Satont**
TODO:

- [x] - find a way to bump all package.json versions via some existed tool. Otherwise write simple node scipt what will update version for each one storage.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
https://lerna.js.org/ maybe?

**Comment by Satont** [comment]
> https://lerna.js.org/ maybe?

It's dead, check repository readme.

**Review by KnorpelSenf — COMMENTED** [review]
LGTM so far, let's solve the remaining tooling things here, too.

**Comment by KnorpelSenf** [comment]
> > [lerna.js.org](https://lerna.js.org/) maybe?
> 
> It's dead, check repository readme.

Right, just saw. Thanks for the heads-up.

**Comment by Satont** [comment]
That seems like i can't test it before everythong another will be done, so it is locked, but probably can be merget and then fixed/changed. I just need that in main for testing purposes, even i'm not like it :/.

**Review by KnorpelSenf — APPROVED** [review]
No problem, it's a big one-time restructuring, so the usual rules don't apply anyway.

**Pull request merged**
