### PR TITLE
fix(firestore): add conversations support

### PR DESCRIPTION
**Pull request by arthurgubaidullin**
I fixed data serialization/deserialization to Firestore document.

The conversation plugin uses an array of arrays structure. This data type is not supported by Firestore.

After my changes, the data will be stored in binary form in the document field.

I also removed the dependency on the package, since they are not needed.

Also this will fix the issue #167.

BREAKING CHANGES: this will most likely reset all sessions.

### CODE REVIEW

**Comment by Satont** [comment]
Why would you store binary in nosql database?

I'm not familat with firestore, insteresting what @KnorpelSenf think, sincw he's author of this adapter.

**Comment by arthurgubaidullin** [comment]
@Satont  There are several reasons:
1) This solves the problem with the `Array<Array<_>>` structure in all sessions at once.
2) Sessions usually do not participate in queries and do not require indexes, which are created automatically for all fields in Firestore. For one field, it is easy to set up a ban on creating an index.
3) Binary data takes up less space and consumes less traffic.
4) The `conversations` plugin data can grow quite quickly due to its nature. Compact data will delay exceeding the limit.

**Review by KnorpelSenf — COMMENTED** [review]
I understand the reasoning behind serialisation and I agree that JSON is the right format here, but why do you want to add all the complexity? This basically is a rewrite of the adapter, and I'd like to understand why :)

**Comment by arthurgubaidullin** [comment]
@KnorpelSenf, I took the initiative to revise the adapter due to its incompatibility with the conversation plugin, as its usage causes the entire application to crash.

If you don't mind, could you please elaborate on the specific challenges you are facing? I would greatly appreciate a detailed explanation.

**Review by KnorpelSenf — APPROVED** [review]
Oh I would've taken the simple path of merely adding (de)serialisation to `packages/firestore/src/index.ts` just like that. I was just wondering why you didn't—but then again, it's definitely a cleaner abstraction to add more interfaces etc.

I assume that you use this adapter actively (in contrast to me)? Would you be available in the future if we need to change something? :)

**Comment by arthurgubaidullin** [comment]
> Oh I would've taken the simple path of merely adding (de)serialisation to packages/firestore/src/index.ts just like that. I was just wondering why you didn't—but then again, it's definitely a cleaner abstraction to add more interfaces etc.

I prefer more explicit code, less room for error.

> I assume that you use this adapter actively (in contrast to me)? 

Right now I'm using my own version of the adapter.

> Would you be available in the future if we need to change something? 

I don't know.

**Comment by KnorpelSenf** [comment]
I'll leave it up to @Satont if he wants to deal with the complexity you introduce. The motivation behind this pull request is reasonable.

**Comment by Satont** [comment]
@arthurgubaidullin rebase please

**Comment by arthurgubaidullin** [comment]
@Satont Something has gone wrong. I don't want to fix it. I do not have time. You can delete PR.

**Pull request closed without merging**
