### PR TITLE
fix(supabase): allow supabase^2 as peer dependency

### PR DESCRIPTION
**Pull request by thecoorum**
This PR adds a supabase^2 as allowed peer dependency to `@grammyjs/storage-supabase`

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
ref #223

**Comment by thecoorum** [comment]
@KnorpelSenf is there anyone else who can review the PR?

**Review by KnorpelSenf — APPROVED** [review]
This LGTM but I'd still like to wait for the opinion of @Satont. I'm sure he'll get to this in a bit when he has time.

**Comment by thecoorum** [comment]
@KnorpelSenf @Satont any updates?

**Comment by Satont** [comment]
Are you sure `1.x` compatible with `2.x` in our case?

**Comment by thecoorum** [comment]
When you asked, I double checked and noticed that `returning: 'minimal'` is deprecated, but seems supabase just ignoring it

**Review by Satont — APPROVED** [review]

**Pull request merged**
