### PR TITLE
chore: replace x/grammyjs with lib.deno.dev and use x/grammyjs without version in examples

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
@Satont They are already lib.deno.dev in the adapters.

**Comment by Satont** [comment]
> @Satont They are already lib.deno.dev in the adapters.

Okay, i see, but not in the README's of adapters. Wan't to do that in the same PR?

**Comment by roj1512** [comment]
@Satont It is not necessary for the READMEs.

**Comment by Satont** [comment]
Thank you.  Are you finished? You just created a PR and then made a few changes.

**Comment by roj1512** [comment]
yes, I am.

**Comment by Satont** [comment]
Thank you contribution.

**Comment by roj1512** [comment]
@satont don't forget the label

**Comment by Satont** [comment]
@roj1512 which one?

**Comment by roj1512** [comment]
hacktoberfest-accepted

**Comment by roj1512** [comment]
also see https://github.com/grammyjs/storages/pull/129

**Pull request merged**
